const SITE={phone:'678-231-4377',text:'470-991-2133',email:'contact@niksremodeling.com'};
const PAGES={
 furniture:{title:'Furniture & Accessories',tag:'Functional. Beautiful. Yours.',desc:'Complete your project with furniture, décor and finishing touches for every room — including custom and repurposed options.',hero:'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1800&q=85',tabs:['All Furniture','Seating','Tables','Storage','Lighting','Décor','Custom & Repurposed']},
 appliances:{title:'Appliances',tag:'Reliable Brands. Real Results.',desc:'Kitchen, laundry and specialty appliances with practical options for delivery, installation and project planning.',hero:'https://images.unsplash.com/photo-1556912167-f556f1f39fdf?auto=format&fit=crop&w=1800&q=85',tabs:['All Appliances','Refrigerators','Ranges','Dishwashers','Microwaves','Laundry','Specialty']},
 cabinets:{title:'Cabinets',tag:'Beautiful. Durable. Designed for Your Home.',desc:'Cabinet solutions for kitchens, baths, storage and custom projects, organized around your space and budget.',hero:'https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=1800&q=85',tabs:['All Cabinets','Base Cabinets','Wall Cabinets','Tall Cabinets','Islands','Vanities','Custom']},
 tools:{title:'Tools',tag:'The Right Tools for the Job.',desc:'Everyday essentials and professional-grade equipment to keep remodeling projects moving.',hero:'https://images.unsplash.com/photo-1530124566582-a618bc2615dc?auto=format&fit=crop&w=1800&q=85',tabs:['All Tools','Power Tools','Hand Tools','Sawing','Drilling','Measuring','Safety']},
 materials:{title:'Materials',tag:'Build It Right from the Start.',desc:'Core remodeling materials organized by project so you can plan quantities, costs and installation together.',hero:'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1800&q=85',tabs:['All Materials','Flooring','Tile & Stone','Drywall','Lumber','Trim','Exterior']},
 supplies:{title:'Supplies',tag:'Everything That Keeps the Job Moving.',desc:'Fasteners, adhesives, paint supplies, plumbing and electrical essentials, protection and jobsite consumables.',hero:'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=1800&q=85',tabs:['All Supplies','Fasteners','Adhesives','Paint','Plumbing','Electrical','Protection']},
 installation:{title:'Installation & Labor',tag:'From the First Idea to the Final Detail.',desc:'Nik’s Remodeling brings the project together, with installation and labor options coordinated around the products and scope you choose.',hero:'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1800&q=85',tabs:['Kitchen','Bathroom','Flooring','Painting','Trim','Exterior','Custom Work']}
};
const images=['https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1556912167-f556f1f39fdf?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1530124566582-a618bc2615dc?auto=format&fit=crop&w=900&q=80'];
function money(n){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n)}
function getCart(){try{return JSON.parse(localStorage.getItem('nr-cart')||'[]')}catch{return[]}}
function saveCart(c){localStorage.setItem('nr-cart',JSON.stringify(c));updateCartCount()}
function updateCartCount(){const n=getCart().reduce((s,x)=>s+(x.qty||1),0);document.querySelectorAll('.cart-count').forEach(e=>e.textContent=n)}
function addItem(name,price,type='Cart'){const c=getCart();const found=c.find(x=>x.name===name);if(found)found.qty=(found.qty||1)+1;else c.push({name,price,qty:1,type});saveCart(c);alert(`${name} added to your ${type.toLowerCase()}.`)}
function header(){return `<div class="topline"><div class="wrap"><div>Office: ${SITE.phone} &nbsp; • &nbsp; Text/Personal: ${SITE.text}</div><div>Supply. Plan. Build. Together.</div></div></div><div class="wrap brandbar"><a class="logo" href="/"><span class="mark"></span><span><strong>NIK'S REMODELING</strong><em>EVERYTHING UNDER ONE ROOF</em></span></a><form class="search" onsubmit="event.preventDefault();alert('Search is ready for product inventory connection.');"><input placeholder="Search products, brands, or projects…"><button>Search</button></form><div class="actions"><a class="cart-pill" href="/project-cart.html">Project Cart <span class="cart-count">0</span></a><a href="tel:${SITE.phone.replaceAll('-','')}">Call</a></div></div><nav class="nav"><div class="wrap"><a href="/">Home</a><a href="/#projects">Shop by Project</a><a href="/materials.html">Materials</a><a href="/supplies.html">Supplies</a><a href="/tools.html">Tools</a><a href="/furniture.html">Furniture & Accessories</a><a href="/appliances.html">Appliances</a><a href="/cabinets.html">Cabinets</a><a href="/installation.html">Installation & Labor</a><a href="/calculators.html">Calculators</a></div></nav>`}
function footer(){return `<footer class="footer"><div class="wrap"><div class="footgrid"><div><h3>Nik's Remodeling</h3><p>Everything under one roof — products, planning and remodeling brought together around the project.</p><p><strong>From the first idea to the final detail, Nik’s Remodeling brings your project together.</strong></p></div><div><h3>Shop</h3><a href="/materials.html">Materials</a><a href="/supplies.html">Supplies</a><a href="/tools.html">Tools</a><a href="/furniture.html">Furniture</a></div><div><h3>Project</h3><a href="/calculators.html">Calculators</a><a href="/installation.html">Installation & Labor</a><a href="/project-cart.html">Project Cart</a></div><div><h3>Contact</h3><a href="tel:${SITE.phone.replaceAll('-','')}">${SITE.phone}</a><a href="sms:${SITE.text.replaceAll('-','')}">${SITE.text}</a><a href="mailto:${SITE.email}">${SITE.email}</a></div></div><div class="fine">© 2026 Nik's Remodeling. All rights reserved. West Georgia & East Alabama.</div></div></footer>`}
function productsFor(p){const names={furniture:['Modern Sofa','Dining Table Set','Accent Chair','Storage Console','Coffee Table','Floor Lamp'],appliances:['French Door Refrigerator','Electric Range','Stainless Dishwasher','Over-the-Range Microwave','Washer & Dryer Set','Range Hood'],cabinets:['Shaker Base Cabinet','Glass Wall Cabinet','Drawer Base Cabinet','Tall Pantry Cabinet','Kitchen Island Cabinet','Vanity Cabinet'],tools:['Cordless Drill Kit','7-1/4 in. Circular Saw','Laser Measure','Oscillating Multi-Tool','Impact Driver','Shop Vacuum'],materials:['Luxury Vinyl Plank','Porcelain Tile','Drywall Sheet','Primed Crown Molding','Pressure-Treated Lumber','Stone Veneer'],supplies:['Construction Adhesive','Deck Screws','Painter Kit','Plumbing Repair Kit','Electrical Essentials','Floor Protection Roll'],installation:['Kitchen Installation','Bathroom Installation','Flooring Installation','Interior Painting','Trim & Finish Work','Custom Project Labor']};return names[p]||[]}
function renderCategory(page){const p=PAGES[page], names=productsFor(page);document.title=`${p.title} | Nik's Remodeling`;document.body.innerHTML=header()+`<main><section class="category-hero" style="--hero-image:url('${p.hero}')"><div class="wrap"><div class="eyebrow">Home / ${p.title}</div><h1>${p.title}</h1><h2>${p.tag}</h2><p>${p.desc}</p></div></section><div class="wrap category-tabs">${p.tabs.map(x=>`<button>${x}</button>`).join('')}</div><section class="section alt"><div class="wrap catalog"><aside class="filters"><h3>Filter</h3><label><input type="checkbox"> In Stock</label><label><input type="checkbox"> Best Value</label><label><input type="checkbox"> Delivery Available</label><label><input type="checkbox"> Installation Option</label></aside><div><h2>Popular ${p.title}</h2><p class="lead">A working starter catalog built from the approved page direction. Product inventory and vendor feeds can be connected without changing this layout.</p><div class="products">${names.map((n,i)=>{const price=[129,249,399,549,799,1199][i];return `<article class="card"><div class="pic"><img src="${images[i%images.length]}" alt="${n}" loading="lazy"></div><div class="body"><div class="stock">In Stock / Available</div><h3>${n}</h3><div class="price">From ${money(price)}</div><div class="card-actions"><button class="add-cart" onclick="addItem('${n.replaceAll("'","\\'")}',${price},'Cart')">Add to Cart</button><button class="add-project" onclick="addItem('${n.replaceAll("'","\\'")}',${price},'Project')">Add to Project</button></div></div></article>`}).join('')}</div></div></div></section></main>`+footer();updateCartCount()}
function renderCalculators(){document.title='Project Calculators | Nik\'s Remodeling';document.body.innerHTML=header()+`<main><section class="category-hero" style="--hero-image:url('https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1800&q=85')"><div class="wrap"><div class="eyebrow">Plan Your Project</div><h1>Project Calculators</h1><p>Get a fast planning number for materials and labor, then add the result to your project.</p></div></section><section class="section"><div class="wrap calc-grid"><div class="panel"><h2>Flooring / Tile</h2><div class="field"><label>Room length (ft)</label><input id="len" type="number" value="12"></div><div class="field"><label>Room width (ft)</label><input id="wid" type="number" value="10"></div><div class="field"><label>Waste allowance</label><select id="waste"><option value="1.1">10%</option><option value="1.15">15%</option><option value="1.2">20%</option></select></div><button class="btn primary" onclick="calcMaterial()">Calculate Material</button><div class="result" id="matres">Enter dimensions and calculate.</div></div><div class="panel"><h2>Labor Planning</h2><div class="field"><label>Project type</label><select id="job"><option value="4.5">Flooring installation</option><option value="7.5">Tile installation</option><option value="3.25">Interior painting</option><option value="8.5">Trim / finish work</option></select></div><div class="field"><label>Estimated project area / units</label><input id="units" type="number" value="120"></div><button class="btn primary" onclick="calcLabor()">Calculate Labor Range</button><div class="result" id="labres">Use this as a planning figure; final scope is verified before work.</div></div></div></section></main>`+footer();updateCartCount()}
function calcMaterial(){const a=(+document.getElementById('len').value||0)*(+document.getElementById('wid').value||0)*(+document.getElementById('waste').value||1);document.getElementById('matres').textContent=`Plan for approximately ${Math.ceil(a)} sq. ft. of material including waste.`}
function calcLabor(){const u=+document.getElementById('units').value||0,r=+document.getElementById('job').value||0,mid=u*r;document.getElementById('labres').textContent=`Planning range: ${money(mid*.85)}–${money(mid*1.15)}. Final labor is confirmed from actual site conditions and scope.`}
function renderCart(){const c=getCart();document.title='Project Cart | Nik\'s Remodeling';document.body.innerHTML=header()+`<main><section class="section"><div class="wrap"><h2>Your Project Cart</h2><p class="lead">Products and project items you save across the site appear here.</p><div class="panel"><div class="cart-list">${c.length?c.map((x,i)=>`<div class="cart-item"><div><strong>${x.name}</strong><div>${x.type||'Cart'} item · Qty ${x.qty||1}</div></div><div>${money((x.price||0)*(x.qty||1))}</div><button class="btn outline" onclick="removeCart(${i})">Remove</button></div>`).join(''):'<div class="empty">Your project cart is empty. Browse products and add items when you are ready.</div>'}</div>${c.length?`<div class="result">Estimated product subtotal: ${money(c.reduce((s,x)=>s+(x.price||0)*(x.qty||1),0))}</div><div class="btns"><a class="btn primary" href="tel:${SITE.phone.replaceAll('-','')}">Call to Review Project</a><a class="btn outline" href="/">Continue Shopping</a></div>`:''}</div></div></section></main>`+footer();updateCartCount()}
function removeCart(i){const c=getCart();c.splice(i,1);saveCart(c);renderCart()}
document.addEventListener('DOMContentLoaded',()=>{const page=document.body.dataset.page;if(PAGES[page])renderCategory(page);else if(page==='calculators')renderCalculators();else if(page==='cart')renderCart();else updateCartCount()});